name: MaskFormer_arxiv

model:
  model:
    init_args:
      mask_decoder:
        init_args:
          loss_config:
            weighting: static
            num_classes: 2
            loss_weights:
              object_class_ce: 0.5
              mask_ce: 12.0
              mask_dice: 8.0
              regression: 2.0
              jets_classification: 1.0
              track_origin: 1.0

            matcher_weights:
              object_class_ce: 2.0
              mask_ce: 10.0
              mask_dice: 2.0
              regression: 2.0
