name: MaskFormer_GLS

model:
  loss_mode: GLS
  model:
    init_args:
      mask_decoder:
        init_args:
          loss_config:
            weighting: GLS
            num_classes: 2
            loss_weights: &loss_weights
              object_class_ce: 1.0
              mask_ce: 1.0
              mask_dice: 1.0
              regression: 1.0
              jets_classification: 1.0
              track_origin: 1.0
  loss_weighting:
    class_path: salt.models.GLS

