name: MaskFormer_equal

model:
  model:
    init_args:
      mask_decoder:
        init_args:
          loss_config:
            weighting: static
            num_classes: 2
            loss_weights:
              object_class_ce: 1.0
              mask_ce: 1.0
              mask_dice: 1.0
              regression: 1.0
              jets_classification: 1.0
              track_origin: 1.0

            matcher_weights:
              object_class_ce: 2.0
              mask_ce: 10.0
              mask_dice: 2.0
              regression: 2.0
